"""
Fannie Mae HomePath Scraper

Scrapes REO property listings from Fannie Mae's HomePath platform.
Working endpoint discovered: GET https://homepath.fanniemae.com/cfl/property-inventory/search

Author: Generated by AI agent
"""

import requests
import json
import time
from datetime import datetime, timezone
from typing import List, Dict, Optional, Any


BASE_URL = "https://homepath.fanniemae.com"
SEARCH_ENDPOINT = f"{BASE_URL}/cfl/property-inventory/search"
PROPERTY_ENDPOINT = f"{BASE_URL}/cfl/property-inventory/property"

DEFAULT_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json, text/plain, */*",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Encoding": "gzip, deflate, br",
    "Referer": "https://homepath.fanniemae.com/listing/search",
    "Connection": "keep-alive",
}


def _parse_timestamp(ts_ms: Optional[int]) -> Optional[str]:
    """Convert milliseconds timestamp to ISO date string."""
    if not ts_ms:
        return None
    try:
        dt = datetime.fromtimestamp(ts_ms / 1000, tz=timezone.utc)
        return dt.strftime("%Y-%m-%d")
    except (TypeError, ValueError, OverflowError):
        return None


def _map_property(raw: Dict[str, Any]) -> Dict[str, Any]:
    """Map a raw HomePath property record to the unified schema."""
    geo = raw.get("geoPoint") or {}
    listing_start = raw.get("listingStartDate")
    first_look_exp = raw.get("firstLookProgramExpiration")

    # Derive a status label
    status = "Active"
    equator = raw.get("equatorStatusLabel", "").lower()
    retail = raw.get("retailStatus", "").lower()
    if equator == "pending" or retail == "under contract":
        status = "Pending"
    elif retail == "price reduced":
        status = "Price Reduced"
    elif retail == "just listed":
        status = "Just Listed"
    elif raw.get("auction"):
        status = "Auction"

    # Build source URL
    property_uuid = raw.get("propertyUuid", "")
    source_url = f"https://homepath.fanniemae.com/property-finder/property/{property_uuid}" if property_uuid else ""

    # Auction date: use firstLookProgramExpiration if present, else listing start
    auction_date = _parse_timestamp(first_look_exp) or _parse_timestamp(listing_start)

    # Description
    desc_parts = [
        f"{raw.get('propertyType', 'Property')} in {raw.get('city', '')}, {raw.get('state', '')}",
    ]
    if raw.get("retailStatus"):
        desc_parts.append(f"Status: {raw['retailStatus']}")
    if raw.get("yearBuilt"):
        desc_parts.append(f"Built in {raw['yearBuilt']}")
    if raw.get("firstLookProgramIndicator"):
        desc_parts.append("First Look Program eligible")
    if raw.get("onlineOfferOnly"):
        desc_parts.append("Online offers only")
    description = " | ".join(desc_parts)

    return {
        "id": f"fannie-{raw.get('propertyUuid', raw.get('reoId', 'unknown'))}",
        "address": raw.get("addressLine1", "").strip(),
        "city": raw.get("city", "").strip(),
        "state": raw.get("state", "").strip(),
        "zip": raw.get("zipCode", "").strip(),
        "price": float(raw.get("price", 0)) if raw.get("price") else 0,
        "estimated_value": float(raw.get("previousPrice", raw.get("price", 0))) if (raw.get("previousPrice") or raw.get("price")) else 0,
        "beds": int(raw.get("bedrooms", 0)) if raw.get("bedrooms") is not None else 0,
        "baths": int(raw.get("bathrooms", 0)) if raw.get("bathrooms") is not None else 0,
        "sqft": int(raw.get("sqft", 0)) if raw.get("sqft") is not None else 0,
        "property_type": raw.get("propertyType", "Unknown"),
        "auction_date": auction_date,
        "auction_type": "REO" if not raw.get("auction") else "REO Auction",
        "source": "Fannie Mae HomePath",
        "source_url": source_url,
        "description": description,
        "image_url": raw.get("primHiResImageUrl", ""),
        "status": status,
        "latitude": float(geo.get("latitude", 0.0)) if geo else 0.0,
        "longitude": float(geo.get("longitude", 0.0)) if geo else 0.0,
    }


def fetch_properties(
    limit: int = 400,
    max_pages: int = 1,
    min_price: Optional[int] = None,
    max_price: Optional[int] = None,
    state: Optional[str] = None,
    delay_seconds: float = 1.0,
) -> List[Dict[str, Any]]:
    """
    Fetch Fannie Mae HomePath REO property listings.

    Args:
        limit: Results per page (max observed ~400).
        max_pages: How many pages to fetch.
        min_price: Optional minimum price filter.
        max_price: Optional maximum price filter.
        state: Optional two-letter state code (e.g. 'FL').
               NOTE: The public endpoint ignores this param server-side;
               filtering is applied client-side after fetch.
        delay_seconds: Sleep between page requests.

    Returns:
        List of property dicts in the unified schema.
    """
    all_properties: List[Dict[str, Any]] = []
    total_fetched = 0

    for page in range(1, max_pages + 1):
        params: Dict[str, Any] = {
            "limit": limit,
            "page": page,
        }
        if min_price is not None:
            params["minPrice"] = min_price
        if max_price is not None:
            params["maxPrice"] = max_price

        try:
            resp = requests.get(
                SEARCH_ENDPOINT,
                headers=DEFAULT_HEADERS,
                params=params,
                timeout=30,
            )
            resp.raise_for_status()
            data = resp.json()
        except requests.exceptions.RequestException as e:
            print(f"[ERROR] Request failed on page {page}: {e}")
            break
        except json.JSONDecodeError as e:
            print(f"[ERROR] Invalid JSON on page {page}: {e}")
            break

        raw_props = data.get("properties", [])
        total_records = data.get("totalProperties", 0)

        if not raw_props:
            print(f"[INFO] No more properties on page {page}. Total fetched: {total_fetched}")
            break

        for raw in raw_props:
            mapped = _map_property(raw)
            # Client-side state filter since server-side param is ignored
            if state and mapped["state"].upper() != state.upper():
                continue
            all_properties.append(mapped)

        total_fetched += len(raw_props)
        print(f"[INFO] Page {page}: fetched {len(raw_props)} raw / {len(all_properties)} matched | total server records: {total_records}")

        if total_fetched >= total_records:
            break

        if page < max_pages:
            time.sleep(delay_seconds)

    return all_properties


def get_property_detail(property_uuid: str) -> Optional[Dict[str, Any]]:
    """
    Fetch detail for a single property by UUID.
    NOTE: The public detail endpoint appears to require authentication;
    this function may return None for unauthenticated access.
    """
    try:
        resp = requests.get(
            PROPERTY_ENDPOINT,
            headers=DEFAULT_HEADERS,
            params={"propertyUuid": property_uuid},
            timeout=30,
        )
        resp.raise_for_status()
        # If we ever get JSON back, map it
        data = resp.json()
        if isinstance(data, dict):
            return _map_property(data)
    except requests.exceptions.RequestException as e:
        print(f"[ERROR] Detail request failed for {property_uuid}: {e}")
    except json.JSONDecodeError:
        print(f"[WARN] Detail endpoint returned non-JSON for {property_uuid} (likely requires auth)")
    return None


# ── Self-test when run directly ──────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("Fannie Mae HomePath Scraper – Self Test")
    print("=" * 60)

    # 1. Small fetch test
    print("\n--- Test 1: Fetch 5 properties (no filters) ---")
    props = fetch_properties(limit=5, max_pages=1)
    print(f"Retrieved {len(props)} properties\n")

    for p in props[:3]:
        print(json.dumps(p, indent=2))
        print("-" * 40)

    # 2. Price-filtered fetch test
    print("\n--- Test 2: Fetch up to 10 properties, price $50k-$150k ---")
    props_filtered = fetch_properties(limit=10, max_pages=1, min_price=50000, max_price=150000)
    print(f"Retrieved {len(props_filtered)} properties\n")
    for p in props_filtered[:3]:
        print(f"  {p['address']}, {p['city']}, {p['state']} {p['zip']}  |  ${p['price']:,.0f}  |  {p['status']}")

    # 3. State-filtered fetch test
    print("\n--- Test 3: Fetch up to 10 properties, state = TX ---")
    props_tx = fetch_properties(limit=50, max_pages=1, state="TX")
    print(f"Retrieved {len(props_tx)} Texas properties\n")
    for p in props_tx[:5]:
        print(f"  {p['address']}, {p['city']}, {p['state']} {p['zip']}  |  ${p['price']:,.0f}")

    # 4. Summary stats
    print("\n--- Summary ---")
    total_all = fetch_properties(limit=400, max_pages=1)
    prices = [p["price"] for p in total_all if p["price"] > 0]
    print(f"Sample page count: {len(total_all)}")
    if prices:
        print(f"Price range in sample: ${min(prices):,.0f} - ${max(prices):,.0f}")
    print("\nDone.")
